# Generated by Django 5.1.2 on 2024-10-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter the username', max_length=50, unique=True)),
                ('email', models.EmailField(help_text='Enter the email address', max_length=100, unique=True)),
                ('password', models.CharField(help_text='Enter the password', max_length=100)),
                ('first_name', models.CharField(help_text='Enter the first name', max_length=100)),
                ('last_name', models.CharField(help_text='Enter the last name', max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
