# Generated by Django 5.1.2 on 2024-10-24 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField(auto_now_add=True, help_text='Loan date')),
                ('return_date', models.DateField(blank=True, help_text='Return date', null=True)),
                ('book', models.ForeignKey(help_text='Select the book being borrowed', on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user', models.ForeignKey(help_text='Select the user who borrows the book', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'loan',
                'verbose_name_plural': 'loans',
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Penalty amount', max_digits=10)),
                ('penalty_date', models.DateField(auto_now_add=True, help_text='Penalty date')),
                ('loan', models.ForeignKey(help_text='Related loan', on_delete=django.db.models.deletion.CASCADE, to='transactions.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(auto_now_add=True, help_text='Reservation date')),
                ('expiration_date', models.DateField(help_text='Expiration date of the reservation')),
                ('book', models.ForeignKey(help_text='Select the book being reserved', on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user', models.ForeignKey(help_text='Select the user who reserves the book', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
            },
        ),
    ]
